apiVersion: v1
kind: ServiceAccount
metadata:
  name: predictive-scaler
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: predictive-scaler-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: predictive-scaler-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: predictive-scaler
  namespace: default
roleRef:
  kind: Role
  name: predictive-scaler-role
  apiGroup: rbac.authorization.k8s.io