apiVersion: v1
kind: Service
metadata:
  name: predictive-scaler
  labels:
    app: predictive-scaler  # Must match your deployment labels
    monitor: metrics
spec:
  selector:
    app: predictive-scaler  # This should match the labels set in the predictive scaler Deployment
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP