apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: predictive-scaler-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: predictive-scaler
  endpoints:
  - port: http
    path: /metrics
    interval: 15s