apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictive-scaler-new
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictive-scaler-new
  template:
    metadata:
      labels:
        app: predictive-scaler-new
    spec:
      containers:
      - name: predictive-scaler
        image: 4dri41/predictive-scaler:fix-final
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: predictive-scaler-pvc
