apiVersion: v1
kind: ServiceAccount
metadata:
  name: predictive-scaler-sa
  namespace: default # Or the namespace where predictive-scaler runs

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: predictive-scaler-metrics-reader
rules:
- apiGroups: [""] # Core API group for pods
  resources: ["pods"]
  verbs: ["get", "list", "watch"] # Need list for label selector, get for requests
- apiGroups: ["metrics.k8s.io"] # Metrics API group
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: predictive-scaler-metrics-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: predictive-scaler-metrics-reader
subjects:
- kind: ServiceAccount
  name: predictive-scaler-sa
  namespace: default # Must match the ServiceAccount's namespace