apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: load-tester-default-fix
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: load-tester-role
  apiGroup: rbac.authorization.k8s.io
