apiVersion: v1
kind: Service
metadata:
  name: load-tester-metrics-service
  namespace: default
  labels:
    app: load-tester-metrics
spec:
  selector:
    app: load-tester
  ports:
  - name: http-metrics
    port: 9105
    targetPort: 9105
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: load-tester-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: load-tester-metrics
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http-metrics
    interval: 15s
