apiVersion: v1
kind: Service
metadata:
  name: product-app-combined-service
  labels:
    app: product-app-combined
spec:
  selector:
    app: product-app-combined
  ports:
  - name: http
    port: 80
    targetPort: 5000
