# scaling-controller-combined.yaml (UPDATED)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-controller-combined
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaling-controller-combined
  template:
    metadata:
      labels:
        app: scaling-controller-combined
    spec:
      serviceAccountName: scaling-controller-sa  # CHANGED!
      containers:
      - name: controller
        image: 4dri4l/scaling-controller:latest
        imagePullPolicy: Always
        env:
        - name: PREDICTIVE_SCALER_SERVICE
          value: "http://predictive-scaler:5000"  # Removed /predict_combined
        - name: TARGET_DEPLOYMENT
          value: "product-app-combined"
        - name: TARGET_NAMESPACE
          value: "default"
        - name: POLL_INTERVAL
          value: "15"
        - name: SCALING_COOLDOWN
          value: "30"
        - name: SCALING_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: product-app-scaling-thresholds
              key: SCALING_THRESHOLD
        - name: CPU_SCALE_UP_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: product-app-scaling-thresholds
              key: CPU_SCALE_UP_THRESHOLD
        - name: CPU_SCALE_DOWN_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: product-app-scaling-thresholds
              key: CPU_SCALE_DOWN_THRESHOLD
        - name: DEBUG_MODE
          value: "true"
        - name: PROMETHEUS_SERVER
          value: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"