# controller-rbac.yaml (COMPLETELY REPLACED)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaling-controller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scaling-controller-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]  # Need to read deployment info
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "update", "patch"]  # Need get to read current scale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaling-controller-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: scaling-controller-sa
  namespace: default
roleRef:
  kind: Role
  name: scaling-controller-role
  apiGroup: rbac.authorization.k8s.io