apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaling-controller
  template:
    metadata:
      labels:
        app: scaling-controller
    spec:
      serviceAccountName: predictive-scaler
      containers:
      - name: controller
        image: 4dri4l/scaling-controller:latest
        imagePullPolicy: Always
        env:
        - name: PREDICTIVE_SCALER_SERVICE
          value: "http://predictive-scaler:5000"  # Fixed: just base URL
        - name: TARGET_DEPLOYMENT
          value: "product-app-combined"  # Fixed: correct deployment name
        - name: TARGET_NAMESPACE
          value: "default"
        - name: POLL_INTERVAL
          value: "60"
        - name: PROMETHEUS_SERVER
          value: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"