apiVersion: v1
kind: ConfigMap
metadata:
  name: product-app-scaling-thresholds
  labels:
    app: product-app
    component: scaling
    managed-by: gitops
  namespace: default
data:
  SCALING_THRESHOLD: "0.5"
  CPU_SCALE_UP_THRESHOLD: "70"
  CPU_SCALE_DOWN_THRESHOLD: "45"
  TARGET_CPU_UTILIZATION: "75"
