apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-apps-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - product-app-hpa
      - product-app-combined
  endpoints:
  - port: http
    path: /metrics
    interval: 15s