apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-app-hpa-monitor
  namespace: monitoring
  labels:
    release: prometheus
    app.kubernetes.io/instance: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: product-app-hpa
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 30s