apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app-hpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-app-hpa
  template:
    metadata:
      labels:
        app: product-app-hpa
    spec:
      containers:
      - name: product-app
        image: 4drial/product-app:latest
        command: ["/bin/sh", "-c"]
        args:
          - "gunicorn --workers 1 --bind 0.0.0.0:5000 --timeout 10 app:app"
        ports:
        - name: http-metrics
          containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: APP_TYPE
          value: "product-app-hpa"