apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app-hpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-app-hpa
  template:
    metadata:
      labels:
        app: product-app-hpa
    spec:
      containers:
      - name: product-app
        image: 4drial/product-app:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - "gunicorn --workers 4 --threads 4 --bind 0.0.0.0:5000 --timeout 30 app:app"
        ports:
        - name: http-metrics
          containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: "300m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        env:
        - name: APP_TYPE
          value: "product-app-hpa"
        - name: MAX_CONCURRENT_REQUESTS
          value: "90"