apiVersion: v1
kind: Service
metadata:
  name: product-app-hpa-service
  labels:
    app: product-app-hpa
spec:
  selector:
    app: product-app-hpa
  ports:
  - name: http
    port: 80
    targetPort: 5000
