apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-controller-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaling-controller-hpa
  template:
    metadata:
      labels:
        app: scaling-controller-hpa
    spec:
      serviceAccountName: scaling-controller-sa  # Changed to match combined
      containers:
      - name: controller
        image: 4dri4l/scaling-controller:latest
        imagePullPolicy: Always
        env:
        - name: PREDICTIVE_SCALER_SERVICE
          value: "http://predictive-scaler:5000"  # Removed /predict endpoint
        - name: TARGET_DEPLOYMENT
          value: "product-app-hpa"
        - name: TARGET_NAMESPACE
          value: "default"
        - name: POLL_INTERVAL
          value: "30"  # Keep slower to let built-in HPA lead
        - name: SCALING_COOLDOWN
          value: "60"
        - name: SCALING_THRESHOLD
          value: "0.5"
        - name: CPU_SCALE_UP_THRESHOLD
          value: "80"
        - name: CPU_SCALE_DOWN_THRESHOLD
          value: "40"
        - name: DEBUG_MODE
          value: "true"
        - name: PROMETHEUS_SERVER
          value: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"