apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-tester
  labels:
    app: load-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-tester
  template:
    metadata:
      labels:
        app: load-tester
    spec:
      containers:
      - name: load-tester
        image: "4dri4l/stress-test:latest"
        imagePullPolicy: Always
        ports:
        - name: metrics
          containerPort: 9105
        # Optional environment overrides can be added here if you need to diverge from
        # the defaults defined in stress-test/load_test.py. Example:
        # env:
        # - name: LOAD_TEST_EXTRA_ARGS
        #   value: "--target hpa"
---
apiVersion: v1
kind: Service
metadata:
  name: load-tester
  labels:
    app: load-tester
spec:
  selector:
    app: load-tester
  ports:
  - name: metrics
    port: 9105
    targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: load-tester-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: load-tester
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
