apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: load-tester-results
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path  # K3s default storage class
