---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-tester
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: load-tester-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: load-tester-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: load-tester
  namespace: default
roleRef:
  kind: Role
  name: load-tester-role
  apiGroup: rbac.authorization.k8s.io
