apiVersion: v1
kind: Pod
metadata:
  name: load-test
  labels:
    app: load-test
spec:
  containers:
  - name: load-test
    image: python:3.9-slim
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    ports:
    - name: metrics
      containerPort: 9105
