apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-tester
  labels:
    app: load-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-tester
  template:
    metadata:
      labels:
        app: load-tester
    spec:
      serviceAccountName: load-tester
      volumes:
      - name: results-storage
        persistentVolumeClaim:
          claimName: load-tester-results
      containers:
      - name: load-tester
        image: "4dri4l/stress-test:latest"
        imagePullPolicy: Always
        ports:
        - name: metrics
          containerPort: 9105
        - name: control-api
          containerPort: 8080
        env:
        - name: CONTROL_API_ENABLED
          value: "true"
        - name: CONTROL_API_PORT
          value: "8080"
        - name: MAX_CONCURRENCY
          value: "24"
        volumeMounts:
        - name: results-storage
          mountPath: /results
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: load-tester
  labels:
    app: load-tester
spec:
  selector:
    app: load-tester
  ports:
  - name: metrics
    port: 9105
    targetPort: metrics
  - name: control-api
    port: 8080
    targetPort: control-api
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: load-tester-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: load-tester
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
