apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: load-test-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: load-test
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
